// Code generated by MockGen. DO NOT EDIT.
// Source: catalog.go

// Package mock_domain is a generated GoMock package.
package mock_domain

import (
	domain "gopds/domain"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockCatalogRepository is a mock of CatalogRepository interface.
type MockCatalogRepository struct {
	ctrl     *gomock.Controller
	recorder *MockCatalogRepositoryMockRecorder
}

// MockCatalogRepositoryMockRecorder is the mock recorder for MockCatalogRepository.
type MockCatalogRepositoryMockRecorder struct {
	mock *MockCatalogRepository
}

// NewMockCatalogRepository creates a new mock instance.
func NewMockCatalogRepository(ctrl *gomock.Controller) *MockCatalogRepository {
	mock := &MockCatalogRepository{ctrl: ctrl}
	mock.recorder = &MockCatalogRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCatalogRepository) EXPECT() *MockCatalogRepositoryMockRecorder {
	return m.recorder
}

// FindAllByParentCatalogEntryID mocks base method.
func (m *MockCatalogRepository) FindAllByParentCatalogEntryID(parentCatalogEntryID string) ([]domain.CatalogEntry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAllByParentCatalogEntryID", parentCatalogEntryID)
	ret0, _ := ret[0].([]domain.CatalogEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAllByParentCatalogEntryID indicates an expected call of FindAllByParentCatalogEntryID.
func (mr *MockCatalogRepositoryMockRecorder) FindAllByParentCatalogEntryID(parentCatalogEntryID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAllByParentCatalogEntryID", reflect.TypeOf((*MockCatalogRepository)(nil).FindAllByParentCatalogEntryID), parentCatalogEntryID)
}

// FindAllFiles mocks base method.
func (m *MockCatalogRepository) FindAllFiles() ([]domain.CatalogEntry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAllFiles")
	ret0, _ := ret[0].([]domain.CatalogEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAllFiles indicates an expected call of FindAllFiles.
func (mr *MockCatalogRepositoryMockRecorder) FindAllFiles() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAllFiles", reflect.TypeOf((*MockCatalogRepository)(nil).FindAllFiles))
}

// FindAllRoots mocks base method.
func (m *MockCatalogRepository) FindAllRoots() ([]domain.CatalogEntry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAllRoots")
	ret0, _ := ret[0].([]domain.CatalogEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAllRoots indicates an expected call of FindAllRoots.
func (mr *MockCatalogRepositoryMockRecorder) FindAllRoots() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAllRoots", reflect.TypeOf((*MockCatalogRepository)(nil).FindAllRoots))
}

// FindByID mocks base method.
func (m *MockCatalogRepository) FindByID(id string) (domain.CatalogEntry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", id)
	ret0, _ := ret[0].(domain.CatalogEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockCatalogRepositoryMockRecorder) FindByID(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockCatalogRepository)(nil).FindByID), id)
}

// Save mocks base method.
func (m *MockCatalogRepository) Save(catalog domain.Catalog) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", catalog)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockCatalogRepositoryMockRecorder) Save(catalog interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockCatalogRepository)(nil).Save), catalog)
}
