name: Main

on:
  push:
    branches: [ main ]
    tags-ignore:
      - v*
  pull_request:
    branches: [ main ]

jobs:
  test-and-build-ui:
    name: Test And Build UI
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 15.x ]
    steps:
      - uses: actions/checkout@v1

      - name: Cache node modules
        id: cache-node
        uses: actions/cache@v2
        with:
          path: ui/node_modules
          key: ${{ runner.os }}-node-${{ secrets.CACHE_VERSION }}-${{ hashFiles('**/package-lock.json') }}

      - name: Node ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        if: steps.cache-node.outputs.cache-hit != 'true'
        run: cd ui && npm install

      - name: Test
        run: cd ui && npm run test -- --watch=false --browsers=ChromeHeadless

      - name: Build
        run: cd ui && npm run build -- --prod --output-path=../public

      - name: Upload UI artifacts
        uses: actions/upload-artifact@v2
        with:
          name: public
          path: public/

  test-and-build-app:
    name: Test And Build App
    runs-on: ubuntu-latest
    needs: [ test-and-build-ui ]
    strategy:
      matrix:
        go-version: [ 1.15.x ]
        platform: [ linux-armv6, linux-amd64 ]
    steps:
      - uses: actions/checkout@v1

      - name: Cache go modules
        id: cache-go
        uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ secrets.CACHE_VERSION }}-${{ hashFiles('**/go.sum') }}

      - name: Go ${{ matrix.go-version }}
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Download UI artifacts
        uses: actions/download-artifact@v2
        with:
          name: public
          path: public/

      - name: Install dependencies
        if: steps.cache-go.outputs.cache-hit != 'true'
        run: go mod download

      - name: Generate
        run: |
          go get -v github.com/golang/mock/mockgen@v1.4.4
          go generate ./...

      - name: Test
        run: go test ./... -v

      - name: Install ARM GCC
        if: matrix.platform == 'linux-armv6'
        run: sudo apt-get -qq -o=Dpkg::Use-Pty=0 install gcc-arm-linux-gnueabi

      - name: Build ${{ matrix.platform }}
        run: |
          make ${{ matrix.platform }}

      - name: Upload ${{ matrix.platform }}
        uses: actions/upload-artifact@v2
        with:
          name: gopds-${{ matrix.platform }}
          path: |
            gopds-${{ matrix.platform }}
            migrations
            public
